name: CI devops 2021 EPF
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - develop
      - master
  pull_request:
jobs:
  build-and-test-app:
    runs-on: ubuntu-18.04
    env: 
      working-directory: ./simple-api
    steps:
      #checkout your github code using actions/checkout@v2.3.3
      - uses: actions/checkout@v2.3.3
      #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: '11'
    #finally build your app with the latest commande
      - name: Build and test with Maven 
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=ncolomb_tp2
            -Dsonar.organization=ncolomb
            -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{
            secrets.SONAR_TOKEN }} --file ./simple-api/pom.xml
  build-and-push-docker-image:
    needs: build-and-test-app
       # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
        # steps to perform in job
    steps:
        - name: Login to DockerHub
          run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN }}
          
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Build image and push backend
          uses: docker/build-push-action@v2
          with:
        # relative path to the place where source code with Dockerfile is located
            context: ./simple-api
          # Note: tags has to be all lower-case
            tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-epf:simple-api
            push: True
        - name: Build image and push database
          uses: docker/build-push-action@v2
          with:
        # relative path to the place where source code with Dockerfile is located
            context: ./database
          # Note: tags has to be all lower-case
            tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-epf:database
            push: True
        - name: Build image and push httpd
          uses: docker/build-push-action@v2
          with:
        # relative path to the place where source code with Dockerfile is located
            context: ./httpd
          # Note: tags has to be all lower-case
            tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-epf:httpd
            push: True
